repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    sha: v1.39.0
    hooks:
      - id: terraform_fmt

  - repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v3.2.0
    hooks:
      - id: check-merge-conflict
